<font face='georgia'>
    
   <h4><strong>What does tf-idf mean?</strong></h4>

   <p>    
Tf-idf stands for <em>term frequency-inverse document frequency</em>, and the tf-idf weight is a weight often used in information retrieval and text mining. This weight is a statistical measure used to evaluate how important a word is to a document in a collection or corpus. The importance increases proportionally to the number of times a word appears in the document but is offset by the frequency of the word in the corpus. Variations of the tf-idf weighting scheme are often used by search engines as a central tool in scoring and ranking a document's relevance given a user query.
</p>
    
   <p>
One of the simplest ranking functions is computed by summing the tf-idf for each query term; many more sophisticated ranking functions are variants of this simple model.
</p>
    
   <p>
Tf-idf can be successfully used for stop-words filtering in various subject fields including text summarization and classification.
</p>
    
</font>

<font face='georgia'>
    <h4><strong>How to Compute:</strong></h4>

Typically, the tf-idf weight is composed by two terms: the first computes the normalized Term Frequency (TF), aka. the number of times a word appears in a document, divided by the total number of words in that document; the second term is the Inverse Document Frequency (IDF), computed as the logarithm of the number of the documents in the corpus divided by the number of documents where the specific term appears.

 <ul>
    <li>
<strong>TF:</strong> Term Frequency, which measures how frequently a term occurs in a document. Since every document is different in length, it is possible that a term would appear much more times in long documents than shorter ones. Thus, the term frequency is often divided by the document length (aka. the total number of terms in the document) as a way of normalization: <br>

$TF(t) = \frac{\text{Number of times term t appears in a document}}{\text{Total number of terms in the document}}.$
</li>
<li>
<strong>IDF:</strong> Inverse Document Frequency, which measures how important a term is. While computing TF, all terms are considered equally important. However it is known that certain terms, such as "is", "of", and "that", may appear a lot of times but have little importance. Thus we need to weigh down the frequent terms while scale up the rare ones, by computing the following: <br>

$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}}.$
for numerical stabiltiy we will be changing this formula little bit
$IDF(t) = \log_{e}\frac{\text{Total  number of documents}} {\text{Number of documents with term t in it}+1}.$
</li>
</ul>

<br>
<h4><strong>Example</strong></h4>
<p>

Consider a document containing 100 words wherein the word cat appears 3 times. The term frequency (i.e., tf) for cat is then (3 / 100) = 0.03. Now, assume we have 10 million documents and the word cat appears in one thousand of these. Then, the inverse document frequency (i.e., idf) is calculated as log(10,000,000 / 1,000) = 4. Thus, the Tf-idf weight is the product of these quantities: 0.03 * 4 = 0.12.
</p>
</font>

### Corpus

In [ ]:
## SkLearn# Collection of string documents

corpus = [
     'this is the first document',
     'this document is the second document',
     'and this is the third one',
     'is this the first document',
]

### SkLearn Implementation

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)
skl_output = vectorizer.transform(corpus)

In [ ]:
# sklearn feature names, they are sorted in alphabetic order by default.

print(vectorizer.get_feature_names())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [ ]:
# Here we will print the sklearn tfidf vectorizer idf values after applying the fit method
# After using the fit function on the corpus the vocab has 9 words in it, and each has its idf value.

print(vectorizer.idf_)

[1.91629073 1.22314355 1.51082562 1.         1.91629073 1.91629073
 1.         1.91629073 1.        ]


In [ ]:
# shape of sklearn tfidf vectorizer output after applying transform method.

skl_output.shape

(4, 9)

In [ ]:
# sklearn tfidf values for first line of the above corpus.
# Here the output is a sparse matrix

print(skl_output[0])

  (0, 8)	0.38408524091481483
  (0, 6)	0.38408524091481483
  (0, 3)	0.38408524091481483
  (0, 2)	0.5802858236844359
  (0, 1)	0.46979138557992045


In [ ]:
# sklearn tfidf values for first line of the above corpus.
# To understand the output better, here we are converting the sparse output matrix to dense matrix and printing it.
# Notice that this output is normalized using L2 normalization. sklearn does this by default.

print(skl_output[0].toarray())

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


### Your custom implementation

In [ ]:
# Write your code here.
# Make sure its well documented and readble with appropriate comments.
# Compare your results with the above sklearn tfidf vectorizer
# You are not supposed to use any other library apart from the ones given below

from collections import Counter
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy


step 1:Implementing the fit method and transform method:

In [ ]:
from tqdm import tqdm 
def fit(dataset):    
    unique_words = set() 
    if isinstance(dataset, (list,)):
        for row in dataset: 
            for word in row.split(" "): 
                if len(word) < 2:
                    continue
                unique_words.add(word)
        unique_words = sorted(list(unique_words))
        vocab = {j:i for i,j in enumerate(unique_words)}
        return vocab
    else:
        print("you need to pass list of sentance")

In [ ]:
from tqdm import tqdm
def transform(dataset,vocab):
    rows = []
    columns = []
    values = []
    if isinstance(dataset, (list,)):
        for idx, row in enumerate(tqdm(dataset)):
            word_freq = dict(Counter(row.split()))
            for word, freq in word_freq.items():                
                if len(word) < 2:
                    continue
                col_index = vocab.get(word, -1)
                if col_index !=-1:
                    rows.append(idx)
                    columns.append(col_index)
                    values.append(freq)
        return csr_matrix((values, (rows,columns)), shape=(len(dataset),len(vocab)))

In [ ]:
strings = ["this is the first document",
           "this document is the second document",
           "and this is the third one",
           "is this the first document"]
        
vocab = fit(strings)
print(list(vocab.keys()))
sparse=transform(strings, vocab).toarray() 
print(sparse)
a=transform(strings, vocab).toarray().shape
print(a)

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


100%|████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]


[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


100%|██████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 4016.57it/s]


(4, 9)


step 2: finding the tf-idf matrix

In [ ]:
lenstring=[len(i.split()) for i in strings]
tfmatrix=[]
for i,k in enumerate(sparse):
    arr=[]
    for j in k:
        z=j/lenstring[i]
        arr.append(z)
    tfmatrix.append(arr)
print("tfmatrix")
print(tfmatrix)

tfmatrix
[[0.0, 0.2, 0.2, 0.2, 0.0, 0.0, 0.2, 0.0, 0.2], [0.0, 0.3333333333333333, 0.0, 0.16666666666666666, 0.0, 0.16666666666666666, 0.16666666666666666, 0.0, 0.16666666666666666], [0.16666666666666666, 0.0, 0.0, 0.16666666666666666, 0.16666666666666666, 0.0, 0.16666666666666666, 0.16666666666666666, 0.16666666666666666], [0.0, 0.2, 0.2, 0.2, 0.0, 0.0, 0.2, 0.0, 0.2]]


In [ ]:
sortedlist=[]
for i,j in vocab.items():
    sortedlist.append(i)
idf=[]
corpus_documents=[["this","is","the","first","document"],["this","document","is","the","second","document"],["and","this","is","the","third","one"],["is","this","the","first","document"]]
a=0
for i in sortedlist:
    a=0
    for j in corpus_documents:
        if i in j:
            a+=1
    idf.append(1+math.log((1+len(corpus_documents))/(1+a)))
print("idf_vector")
print(idf)

['is', 'this', 'the', 'first', 'document']
idf_vector
[1.916290731874155, 1.2231435513142097, 1.5108256237659907, 1.0, 1.916290731874155, 1.916290731874155, 1.0, 1.916290731874155, 1.0]


In [ ]:
c=[]
for i in tfmatrix:
    b=[]
    for j,k in enumerate(i):
        a=k*idf[j]
        b.append(a)
    c.append(b)
print("tf-idfmatrix")
print(c)

tf-idfmatrix
[[0.0, 0.24462871026284194, 0.3021651247531982, 0.2, 0.0, 0.0, 0.2, 0.0, 0.2], [0.0, 0.40771451710473655, 0.0, 0.16666666666666666, 0.0, 0.3193817886456925, 0.16666666666666666, 0.0, 0.16666666666666666], [0.3193817886456925, 0.0, 0.0, 0.16666666666666666, 0.3193817886456925, 0.0, 0.16666666666666666, 0.3193817886456925, 0.16666666666666666], [0.0, 0.24462871026284194, 0.3021651247531982, 0.2, 0.0, 0.0, 0.2, 0.0, 0.2]]


step 3: Applying l2 normalization:

In [ ]:
tfidf=normalize(c,norm='l2',axis=1)
print(tfidf)

[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


In [ ]:
tfidf[0]

array([0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
       0.        , 0.38408524, 0.        , 0.38408524])

<font face='georgia'>
    <h4><strong>2. Implement max features functionality:</strong></h4>

<ul>
    <li> As a part of this task you have to modify your fit and transform functions so that your vocab will contain only 50 terms with top idf scores.</li>
    <br>
    <li>This task is similar to your previous task, just that here your vocabulary is limited to only top 50 features names based on their idf values. Basically your output will have exactly 50 columns and the number of rows will depend on the number of documents you have in your corpus.</li>
    <br>
    <li>Here you will be give a pickle file, with file name <strong>cleaned_strings</strong>. You would have to load the corpus from this file and use it as input to your tfidf vectorizer.</li>
    <br>
    <li>Steps to approach this task:
    <ol>
        <li> You would have to write both fit and transform methods for your custom implementation of tfidf vectorizer, just like in the previous task. Additionally, here you have to limit the number of features generated to 50 as described above.</li>
        <li> Now sort your vocab based in descending order of idf values and print out the words in the sorted voacb after you fit your data. Here you should be getting only 50 terms in your vocab. And make sure to print idf values for each term in your vocab. </li>
        <li> Make sure the output of your implementation is a sparse matrix. Before generating the final output, you need to normalize your sparse matrix using L2 normalization. You can refer to this link https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html </li>
        <li> Now check the output of a single document in your collection of documents,  you can convert the sparse matrix related only to that document into dense matrix and print it. And this dense matrix should contain 1 row and 50 columns. </li>
        </ol>
    </li>
    <br>
   </ul>

In [ ]:
from collections import Counter
from scipy.sparse import csr_matrix
import math
import operator
from sklearn.preprocessing import normalize
import numpy
import pickle
with open('cleaned_strings', 'rb') as f:
    corpus_pickle = pickle.load(f)
    
# printing the length of the corpus loaded
print("Number of documents in corpus = ",len(corpus_pickle))

Number of documents in corpus =  746


step1: viewing the whole corpus unique word by general fit method

In [ ]:
from tqdm import tqdm 
def fit(dataset):    
    unique_words = set() 
    if isinstance(dataset, (list,)):
        for row in dataset: 
            for word in row.split(" "): 
                if len(word) < 2:
                    continue
                unique_words.add(word)
        unique_words = sorted(list(unique_words))
        vocab = {j:i for i,j in enumerate(unique_words)}
        return vocab
    else:
        print("you need to pass list of sentance")
vocab = fit(corpus_pickle)

step 2:Modifying the fit method and taking of top 50 idf value of unique words in the whole unique words in corpus_pickle

In [ ]:
sortedlist=[]
for i,j in vocab.items():
    sortedlist.append(i)
idf=[]
a=0
for i in corpus_pickle:
    a=i.split()
for i in sortedlist:
    a=0
    for j in corpus_pickle:
        if i in j:
            a+=1
    idf.append(1+math.log((1+len(corpus_pickle))/(1+a)))
q=[]
for i in zip(idf,sortedlist):
    q.append(i)
q.sort(reverse=True)
x=q[0:50]
s=[]
v=[]
for i in x:
    for j in range(1):
        s.append(i[1])
        v.append(i[0])
print("\n")
print("top 50 idf vocab")
print(s)
print(len(s))
print("\n")
print("idf value of the vocab")
print(v)
print(len(v))
    



top 50 idf vocab
['zombiez', 'zillion', 'yun', 'youtube', 'youthful', 'younger', 'yelps', 'yawn', 'yardley', 'wrote', 'writers', 'wrap', 'wow', 'woven', 'wouldnt', 'worthwhile', 'worthless', 'worry', 'worked', 'wont', 'wong', 'wondered', 'woa', 'witticisms', 'within', 'wily', 'willie', 'william', 'wild', 'wih', 'wife', 'widmark', 'wide', 'whoever', 'whites', 'whine', 'whenever', 'went', 'welsh', 'weight', 'wedding', 'website', 'weaving', 'weariness', 'weaker', 'wayne', 'waylaid', 'wave', 'wasting', 'waster']
50


idf value of the vocab
[6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872, 6.922918004572872,

step 3:genearting the sparse matrix and tranform method

In [ ]:
tf=[]
for k in corpus_pickle:
    temp=[]
    for i in s:
        cnt=0
        words=k.split()
        for j in words:
            if i == j:
                cnt+=1
        temp.append(cnt)
    tf.append(temp)

In [ ]:
len(tf)

746

In [ ]:
numpy.array(tf).shape

(746, 50)

step 4: generating tfmatrix:

In [ ]:
lenstring=[len(i.split()) for i in corpus_pickle]
tfmatrix=[]
for i,k in enumerate(tf):
    arr=[]
    for j in k:
        z=j/lenstring[i]
        arr.append(z)
    tfmatrix.append(arr)



In [ ]:
len(tfmatrix)

746

In [ ]:
numpy.array(tfmatrix).shape

(746, 50)

step5: Generating TF-IDF matrix:

In [ ]:
c=[]
for i in tfmatrix:
    b=[]
    for j,k in enumerate(i):
        a=k*v[j]
        b.append(a)
    c.append(b)

In [ ]:
len(c) 

746

In [ ]:
numpy.array(tfmatrix).shape

(746, 50)

step6:Applying l2 normalization of tf-idf matrix:

In [ ]:
tfidf=normalize(c,norm='l2',axis=1)
print(tfidf)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
tfidf[0] #tfidf matrix of the 0th row after l2 normalization

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])